site_name: Tietoverkkokurssin dokumentaatio
site_description: Tietoverkkokurssin dokumentaatio
site_author: Herkko Mehtälä / JAMK

theme:
  name: material
  language: 'en'
  history_buttons: false
  article_nav_bottom: false
  article_nav_top: false